# Generated by Django 2.2.16 on 2020-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='auth',
            field=models.TextField(default='N/A'),
        ),
    ]
