# Generated by Django 2.2.16 on 2021-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_login_model_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='link',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='login_model',
            name='auth',
            field=models.TextField(default='member'),
        ),
    ]
