# Generated by Django 2.2.16 on 2020-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice_model',
            old_name='auth',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notice_model',
            old_name='username',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notice_model',
            old_name='password',
            new_name='issuer',
        ),
        migrations.AddField(
            model_name='notice_model',
            name='subject',
            field=models.TextField(default='N/A'),
        ),
    ]
