# Generated by Django 2.2.16 on 2020-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.TextField(default='n/a')),
                ('content', models.TextField(default='N/A')),
                ('date', models.TextField(default='N/A')),
            ],
        ),
    ]
