# Generated by Django 2.2.16 on 2020-11-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
