# Generated by Django 2.2.16 on 2020-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(default='n/a')),
                ('receiver', models.TextField(default='N/A')),
                ('message', models.TextField(default='N/A')),
            ],
        ),
    ]
