# Generated by Django 2.2.16 on 2020-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_model',
            name='date',
            field=models.TextField(default='N/A'),
        ),
    ]
