# Generated by Django 2.2.16 on 2021-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='water_tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(default='n/a')),
                ('pump_status', models.TextField(default='N/A')),
                ('automations_status', models.TextField(default='N/A')),
            ],
        ),
    ]
