# Generated by Django 2.2.16 on 2021-02-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water_tank',
            old_name='automations_status',
            new_name='automation_status',
        ),
    ]
