# Generated by Django 2.2.16 on 2021-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210211_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='lights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_lights', models.TextField(default='n/a')),
                ('floor_no', models.TextField(default='N/A')),
                ('floor_lights', models.TextField(default='N/A')),
                ('scheduled_time', models.TextField(default='n/a')),
                ('all_lights', models.TextField(default='N/A')),
            ],
        ),
    ]
