# Generated by Django 2.2.16 on 2021-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_lights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lights',
            old_name='scheduled_time',
            new_name='scheduled_time_from',
        ),
        migrations.AddField(
            model_name='lights',
            name='scheduled_time_to',
            field=models.TextField(default='n/a'),
        ),
    ]
