# Generated by Django 2.2.16 on 2021-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210212_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='lights_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(default='n/a')),
            ],
        ),
        migrations.CreateModel(
            name='water_tank_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(default='n/a')),
            ],
        ),
    ]
