# Generated by Django 2.2.16 on 2021-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_lights_date_water_tank_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lights',
            name='all_lights',
            field=models.TextField(default='false'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='floor_lights',
            field=models.TextField(default='false'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='floor_no',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='scheduled_lights',
            field=models.TextField(default='false'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='scheduled_time_from',
            field=models.TextField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='scheduled_time_to',
            field=models.TextField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='water_tank',
            name='automation_status',
            field=models.TextField(default='false'),
        ),
        migrations.AlterField(
            model_name='water_tank',
            name='level',
            field=models.TextField(default='40'),
        ),
        migrations.AlterField(
            model_name='water_tank',
            name='pump_status',
            field=models.TextField(default='false'),
        ),
    ]
