# Generated by Django 2.2.16 on 2021-02-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_login_model',
            name='email',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='new_login_model',
            name='flat',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='new_login_model',
            name='floor',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='new_login_model',
            name='link',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='new_login_model',
            name='wing',
            field=models.TextField(default='n/a'),
        ),
    ]
