# Generated by Django 2.2.16 on 2021-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit_timestamp', '0002_auto_20210215_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_exit_model',
            name='date',
            field=models.TextField(default='n/a'),
        ),
    ]
